version: "3"
services:
  cockroach:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - roachnet
    command: start --insecure
  db-init:
    image: cockroachdb/cockroach:latest
    networks:
      - roachnet
    depends_on:
      - cockroach
    volumes:
      - ./cockroach/setup_db.sh:/setup_db.sh
    entrypoint: "/bin/bash"
    command: /setup_db.sh

networks:
  roachnet: